export const HOME_SELECT = "HOME_SELECT";
export const SINGLE_TUNNEL_NOTIFICATION_REQUEST =
  "SINGLE_TUNNEL_NOTIFICATION_REQUEST";
export const SINGLE_TUNNEL_NOTIFICATION_SUCCESS =
  "SINGLE_TUNNEL_NOTIFICATION_SUCCESS";
export const SINGLE_TUNNEL_NOTIFICATION_FAILURE =
  "SINGLE_TUNNEL_NOTIFICATION_FAILURE";
export const TELEMETRY_REQUEST = "TELEMETRY_REQUEST";
export const TELEMETRY_SUCCESS = "TELEMETRY_SUCCESS";
export const TELEMETRY_FAILURE = "TELEMETRY_FAILURE";
