export const SMEOPS_SELECT = "SMEOPS_SELECT";
export const REPLACE_INSTANCE_REQUEST = "REPLACE_INSTANCE_REQUEST";
export const REPLACE_INSTANCE_SUCCESS = "REPLACE_INSTANCE_SUCCESS";
export const REPLACE_INSTANCE_FAILURE = "REPLACE_INSTANCE_FAILURE";
export const GET_CUSTOMER_LIMIT_REQUEST = "GET_CUSTOMER_LIMIT_REQUEST";
export const GET_CUSTOMER_LIMIT_SUCCESS = "GET_CUSTOMER_LIMIT_SUCCESS";
export const GET_CUSTOMER_LIMIT_FAILURE = "GET_CUSTOMER_LIMIT_FAILURE";
export const PIN_CUSTOMER_ACCOUNT_TO_INSTANCE_SIZE_REQUEST =
  "PIN_CUSTOMER_ACCOUNT_TO_INSTANCE_REQUEST";
export const PIN_CUSTOMER_ACCOUNT_TO_INSTANCE_SIZE_SUCCESS =
  "PIN_CUSTOMER_ACCOUNT_TO_INSTANCE_SUCCESS";
export const PIN_CUSTOMER_ACCOUNT_TO_INSTANCE_SIZE_FAILURE =
  "PIN_CUSTOMER_ACCOUNT_TO_INSTANCE_FAILURE";
export const PIN_CUSTOMER_TO_AMI_REQUEST = "PIN_CUSTOMER_TO_AMI_REQUEST";
export const PIN_CUSTOMER_TO_AMI_SUCCESS = "PIN_CUSTOMER_TO_AMI_SUCCESS";
export const PIN_CUSTOMER_TO_AMI_FAILURE = "PIN_CUSTOMER_TO_AMI_FAILURE";
export const PING_FROM_INSTANCE_REQUEST = "PING_FROM_INSTANCE_REQUEST";
export const PING_FROM_INSTANCE_SUCCESS = "PING_FROM_INSTANCE_SUCCESS";
export const PING_FROM_INSTANCE_FAILURE = "PING_FROM_INSTANCE_FAILURE";
export const TCP_DUMP_REQUEST = "TCP_DUMP_REQUEST";
export const TCP_DUMP_SUCCESS = "TCP_DUMP_INSTANCE_SUCCESS";
export const TCP_DUMP_FAILURE = "TCP_DUMP_FAILURE";
